### ISSUE TITLE
Not working on angular 8

### ISSUE THREAD

**Issue by spiko-md** [awerlang/observable-profiler#3]
Cannot get it working. When I tried using it on a real project it errors out with multiple errors, e.g. at index.js:202 Error at new SubscriptionSource (index.js:79) at EventEmitter.subscribe (index.js:112) at EventEmitter.push../node_modules/@angular/core/fesm5/core.js.EventEmitter.subscribe (core.js:22123) at TooltipDirective.push../node_modules/ngx-bootstrap/tooltip/fesm5/ngx-bootstrap-tooltip.js.TooltipDirective.ngOnInit (ngx-bootstrap-tooltip.js:332) at checkAndUpdateDirectiveInline (core.js:19341) at checkAndUpdateNodeInline (core.js:27597) at checkAndUpdateNode (core.js:27559) ... 

On repro it just doesn't seem to work at all (well the print function does not seem to work)

repro: https://github.com/spiko-md/repro-observable-profiler-1

**Comment by awerlang** [comment]
Hello!

The stack trace pasted above points to a subscription on the tooltip component (at `TooltipDirective.ngOnInit`) that isn't being disposed. It either might be disposed at a later time e.g. the routed component is unloaded, or it is in fact a memory leak. In case it's a memory leak, it's likely to be the 3rd-party component's fault. Nothing you can do to fix that except to report to the 3rd-party, or not using the component at all.

The output of the print function is styled as regular errors. Maybe you took that as errors _in_ this tool? They're not, this style allows to print stack traces as well, which makes it easier to spot where the leaking subscriptions are.

At first glance your repro doesn't seem to make any subscriptions, that's why the print function doesn't print anything. You construct a `Subject`, but no subscription to it is made. If you include a `.subscribe()` to it there should be an item printed out.

Hope this clears any misunderstanding about how the tool works. Any day I should improve the docs on this.

**Comment by spiko-md** [comment]
Hi,

yes, I understood the error printout as errors in the tool :) My first reaction was "I cannot have this many open subscriptions" so I took the errors as incompatibilities with newer angular then the docs are written for - I was unsure if it would even work.

The output could probably be improved by mentioning it is a stack trace to where subscription occurred. 

Also, the number of reported subscriptions/printed lines does not seem to match:
Current subscriptions (including indirect/nested): 5
//Lines of output: 3

Can you please look at the updated repro anyway? I added a real subscription to interval, which is not being printed out, even though it lives on after leaving the test page.

**Comment by awerlang** [comment]
> Also, the number of reported subscriptions/printed lines does not seem to match:
> Current subscriptions (including indirect/nested): 5
> //Lines of output: 3

Indirect subscriptions are omitted by default. `printSubscribers({ reportInnerSubscriptions: true })` should report all of them.

> Can you please look at the updated repro anyway? I added a real subscription to interval, which is not being printed out, even though it lives on after leaving the test page.

Using the router recipe, subscription tracking begins when the routed component is activated i.e. after its construction. Besides I advise never to subscribe in constructors. I moved the subscription to `ngOnInit` as it's a better practice, then the leak is reported to console.

The router recipe is intended to catch leaks as fast and localized as possible. Once you're done with router tests, use the bootstrap recipe, which would catch many more leaks, including work done outside router.

Happy bug fixing! ;)

**Comment by awerlang** [comment]
Hello, have you got time to look at it again?

Cheers

**Comment by spiko-md** [comment]
Hi, I tried again and now that I understand how the tool works I think you can close this issue. I get reports about several unclosed subscriptions, but I think most are cleaned up since I don't see them on further requests.
Thank you
